# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import beagle_pb2 as beagle__pb2


class BeagleboneStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Beagle = channel.unary_unary(
                '/Beaglebone/Beagle',
                request_serializer=beagle__pb2.Jetson_to_beagle.SerializeToString,
                response_deserializer=beagle__pb2.Logging_Packet.FromString,
                )


class BeagleboneServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Beagle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BeagleboneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Beagle': grpc.unary_unary_rpc_method_handler(
                    servicer.Beagle,
                    request_deserializer=beagle__pb2.Jetson_to_beagle.FromString,
                    response_serializer=beagle__pb2.Logging_Packet.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Beaglebone', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Beaglebone(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Beagle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Beaglebone/Beagle',
            beagle__pb2.Jetson_to_beagle.SerializeToString,
            beagle__pb2.Logging_Packet.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
