# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beagle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x65\x61gle.proto\"4\n\x10Jetson_to_beagle\x12\x14\n\x0ckeyboard_cmd\x18\x01 \x01(\r\x12\n\n\x02xf\x18\x02 \x03(\x02\"(\n\x0eLogging_Packet\x12\x16\n\x04logs\x18\x01 \x03(\x0b\x32\x08.Logging\"\xa5\x06\n\x07Logging\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\r\n\x05x_ego\x18\x02 \x01(\x02\x12\r\n\x05y_ego\x18\x03 \x01(\x02\x12\x11\n\ttheta_ego\x18\x04 \x01(\x02\x12 \n\x18moteus1_current_position\x18\x05 \x01(\x02\x12 \n\x18moteus2_current_position\x18\x06 \x01(\x02\x12 \n\x18moteus1_current_velocity\x18\x07 \x01(\x02\x12 \n\x18moteus2_current_velocity\x18\x08 \x01(\x02\x12\x1e\n\x16moteus1_torque_reading\x18\t \x01(\x02\x12\x1e\n\x16moteus2_torque_reading\x18\n \x01(\x02\x12\x1e\n\x16moteus1_torque_command\x18\x0b \x01(\x02\x12\x1e\n\x16moteus2_torque_command\x18\x0c \x01(\x02\x12\x19\n\x11\x64t_moteus_control\x18\r \x01(\x02\x12\x15\n\rpitch_angle85\x18\x0e \x01(\x02\x12\x13\n\x0byaw_angle85\x18\x0f \x01(\x02\x12\x14\n\x0cpitch_rate85\x18\x10 \x01(\x02\x12\x12\n\nyaw_rate85\x18\x11 \x01(\x02\x12\x18\n\x10pitch_rate85_ewa\x18\x12 \x01(\x02\x12\x16\n\x0eyaw_rate85_ewa\x18\x13 \x01(\x02\x12\x18\n\x10\x64t_imu85_process\x18\x14 \x01(\x02\x12\x1a\n\x12\x64t_logging_process\x18\x15 \x01(\x02\x12\x12\n\nz_position\x18\x16 \x01(\x02\x12\x12\n\nz_velocity\x18\x17 \x01(\x02\x12\x15\n\rz_pitch_angle\x18\x18 \x01(\x02\x12\x14\n\x0cz_pitch_rate\x18\x19 \x01(\x02\x12\x13\n\x0bz_yaw_angle\x18\x1a \x01(\x02\x12\x12\n\nz_yaw_rate\x18\x1b \x01(\x02\x12\x12\n\nx_position\x18\x1c \x01(\x02\x12\x12\n\nx_velocity\x18\x1d \x01(\x02\x12\x15\n\rx_pitch_angle\x18\x1e \x01(\x02\x12\x14\n\x0cx_pitch_rate\x18\x1f \x01(\x02\x12\x13\n\x0bx_yaw_angle\x18  \x01(\x02\x12\x12\n\nx_yaw_rate\x18! \x01(\x02\x32<\n\nBeaglebone\x12.\n\x06\x42\x65\x61gle\x12\x11.Jetson_to_beagle\x1a\x0f.Logging_Packet\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'beagle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JETSON_TO_BEAGLE._serialized_start=16
  _JETSON_TO_BEAGLE._serialized_end=68
  _LOGGING_PACKET._serialized_start=70
  _LOGGING_PACKET._serialized_end=110
  _LOGGING._serialized_start=113
  _LOGGING._serialized_end=918
  _BEAGLEBONE._serialized_start=920
  _BEAGLEBONE._serialized_end=980
# @@protoc_insertion_point(module_scope)
